name: Lucky Number

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lucky-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Fetch and merge latest changes
        run: |
          git fetch origin
          git merge --strategy-option=ours --allow-unrelated-histories origin/main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run app.py
        id: lucky
        run: |
          python main.py
          echo "Contents of lucky_number.txt:"
          cat output/lucky_number.txt

      - name: Commit and push changes
        run: |
          git add -A
          COMMIT_MSG=$(cat output/lucky_number.txt)
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          git push origin HEAD:main --force
